server:
  port: 8085

spring:
  cloud:
    stream:
      bindings:
        inboundSynthesisRequest:
          destination: synthesisRequestTopic
          content-type: application/json
          group: synthesisGroup
          consumer:
            concurrency: 6
        outboundSynthesisComplete:
          destination: synthesisCompleteTopic
          content-type: application/json
          producer:
            partitionCount: 20
      kafka:
        binder:
          brokers: localhost
          autoAddPartitions: true

logging:
  level:
    style.everywear: debug