server:
  port: 8085

spring:
  cloud:
    stream:
      bindings:
        inboundSynthesisRequest:
          destination: synthesisRequestTopic
          content-type: application/json
          group: synthesisGroup
          consumer:
            concurrency: 6
        outboundSynthesisComplete:
          destination: synthesisCompleteTopic
          content-type: application/json
          producer:
            partitionCount: 20
      kafka:
        binder:
          brokers: localhost
          autoAddPartitions: true

logging:
  level:
    style.everywear: debug

jib.extras:
    saved-model-path: /Users/jun097kim/dev/CycleGAN-TensorFlow/savedmodel/1
    upload-output-path: /Users/jun097kim/dev/everywear-model-server/uploads/output