server:
  port: 8085

spring:
  cloud:
    stream:
      bindings:
        inboundSynthesisRequest:
          destination: synthesisRequestTopic
          content-type: application/json
          group: synthesisGroup
          consumer:
            concurrency: 6
        outboundSynthesisComplete:
          destination: synthesisCompleteTopic
          content-type: application/json
          producer:
            partitionCount: 20
      kafka:
        binder:
          brokers: localhost
          autoAddPartitions: true

logging:
  level:
    style.everywear: debug

jib.extras:
    saved-model:
      gmm-path: /Users/jun097kim/dev/everywear-model-server/ew-synthesis/jib-extras/savedmodel-gmm/1
      edm-path: /Users/jun097kim/dev/everywear-model-server/ew-synthesis/jib-extras/savedmodel-edm/1
      rm-path: /Users/jun097kim/dev/everywear-model-server/ew-synthesis/jib-extras/savedmodel-rm/1
    upload-output-path: /Users/jun097kim/dev/everywear-model-server/uploads/users/jun097kim/output/stage2/